site_name: 'OFT docs'

theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'images/favicon.ico'
  logo:
    icon: 'import_contacts'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: true
  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra:
  social:
    - type: 'facebook'
      link: 'https://facebook.com/paycore.io/'
    - type: 'twitter'
      link: 'https://twitter.com/paycoreio'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/paycore/'
    - type: 'github'
      link: 'https://github.com/paycoreio'
extra_css:
  - extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
      repo_url_shorthand: true
      user: paycoreio
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details

nav:
  -
    Providers:
      -
        Overview: payment-providers/index.md
      -
        123x: payment-providers/123x/index.md
      -
        1pay: payment-providers/1pay/index.md
      -
        4bill: payment-providers/4bill/index.md
      -
        Acceptance: payment-providers/acceptance/index.md
      -
        Africanpaymentsolutions: payment-providers/africanpaymentsolutions/index.md
      -
        Anycash: payment-providers/anycash/index.md
      -
        Aramorpayments: payment-providers/aramorpayments/index.md
      -
        Astropay: payment-providers/astropay/index.md
      -
        Balticpay: payment-providers/balticpay/index.md
      -
        Beanstream: payment-providers/beanstream/index.md
      -
        Billtomobile: payment-providers/billtomobile/index.md
      -
        Bips: payment-providers/bips/index.md
      -
        Bitmerch: payment-providers/bitmerch/index.md
      -
        Bitnet: payment-providers/bitnet/index.md
      -
        Bitpay: payment-providers/bitpay/index.md
      -
        Bscardservices: payment-providers/bscardservices/index.md
      -
        Bucksnet: payment-providers/bucksnet/index.md
      -
        Cardconnect: payment-providers/cardconnect/index.md
      -
        Cashsender: payment-providers/cashsender/index.md
      -
        Circulopayments: payment-providers/circulopayments/index.md
      -
        Citopay: payment-providers/citopay/index.md
      -
        Citruspay: payment-providers/citruspay/index.md
      -
        Corvuspay: payment-providers/corvuspay/index.md
      -
        Credorax: payment-providers/credorax/index.md
      -
        Cxpay: payment-providers/cxpay/index.md
      -
        Cyberbit: payment-providers/cyberbit/index.md
      -
        Dalberry: payment-providers/dalberry/index.md
      -
        Digitalriverworldpayments: payment-providers/digitalriverworldpayments/index.md
      -
        Dineromail: payment-providers/dineromail/index.md
      -
        Dinpay: payment-providers/dinpay/index.md
      -
        Dlocal: payment-providers/dlocal/index.md
      -
        Ecardsa: payment-providers/ecardsa/index.md
      -
        Econtext: payment-providers/econtext/index.md
      -
        Ecpss: payment-providers/ecpss/index.md
      -
        Eospaymentsolutions: payment-providers/eospaymentsolutions/index.md
      -
        Epay: payment-providers/epay/index.md
      -
        Europayment: payment-providers/europayment/index.md
      -
        Europaysolutions: payment-providers/europaysolutions/index.md
      -
        Exacttransactions: payment-providers/exacttransactions/index.md
      -
        Expercash: payment-providers/expercash/index.md
      -
        Ezic: payment-providers/ezic/index.md
      -
        Firstatlanticcommerce: payment-providers/firstatlanticcommerce/index.md
      -
        Flashpay: payment-providers/flashpay/index.md
      -
        Fondy: payment-providers/fondy/index.md
      -
        Gestpay: payment-providers/gestpay/index.md
      -
        Iyzipayments: payment-providers/iyzipayments/index.md
      -
        Kortapay: payment-providers/kortapay/index.md
      -
        Lateralpaymentsolutions: payment-providers/lateralpaymentsolutions/index.md
      -
        Lianlianpay: payment-providers/lianlianpay/index.md
      -
        Liqpay: payment-providers/liqpay/index.md
      -
        Magnius: payment-providers/magnius/index.md
      -
        Mangopay: payment-providers/mangopay/index.md
      -
        Masterpayment: payment-providers/masterpayment/index.md
      -
        Merchantscout: payment-providers/merchantscout/index.md
      -
        Mollie: payment-providers/mollie/index.md
      -
        Netmobileag: payment-providers/netmobileag/index.md
      -
        Netpay: payment-providers/netpay/index.md
      -
        Omnipayment: payment-providers/omnipayment/index.md
      -
        Onpex: payment-providers/onpex/index.md
      -
        Optomany: payment-providers/optomany/index.md
      -
        Payanyway: payment-providers/payanyway/index.md
      -
        Paybox: payment-providers/paybox/index.md
      -
        Paycific: payment-providers/paycific/index.md
      -
        Paydoo: payment-providers/paydoo/index.md
      -
        Paymega: payment-providers/paymega/index.md
      -
        Paymentexpress: payment-providers/paymentexpress/index.md
      -
        Paymentgarage: payment-providers/paymentgarage/index.md
      -
        Paymentgateway: payment-providers/paymentgateway/index.md
      -
        Paymundo: payment-providers/paymundo/index.md
      -
        Paystation: payment-providers/paystation/index.md
      -
        Paytabs: payment-providers/paytabs/index.md
      -
        Pinpayments: payment-providers/pinpayments/index.md
      -
        Propay: payment-providers/propay/index.md
      -
        Realexpayments: payment-providers/realexpayments/index.md
      -
        Robokassa: payment-providers/robokassa/index.md
      -
        Sbm: payment-providers/sbm/index.md
      -
        Securepay: payment-providers/securepay/index.md
      -
        Securionpay: payment-providers/securionpay/index.md
      -
        Simplepay: payment-providers/simplepay/index.md
      -
        Sisow: payment-providers/sisow/index.md
      -
        Sixpaymentservices: payment-providers/sixpaymentservices/index.md
      -
        Swishme: payment-providers/swishme/index.md
      -
        Tefpay: payment-providers/tefpay/index.md
      -
        Test: payment-providers/test/index.md
      -
        Trustpay: payment-providers/trustpay/index.md
      -
        Upclick: payment-providers/upclick/index.md
      -
        Vallettapay: payment-providers/vallettapay/index.md
      -
        Wayforpay: payment-providers/wayforpay/index.md
      -
        Webmoney: payment-providers/webmoney/index.md
      -
        Yandexcheckout: payment-providers/yandexcheckout/index.md
      -
        Yandexmoney: payment-providers/yandexmoney/index.md
      -
        Yapstone: payment-providers/yapstone/index.md
      -
        Zaakpay: payment-providers/zaakpay/index.md
  -
    'Payout services':
      -
        Overview: payout-services/index.md
      -
        Advcash_wallet_rub: payout-services/advcash_wallet_rub/index.md
      -
        Advcash_wallet_uah: payout-services/advcash_wallet_uah/index.md
      -
        Advcash_wallet_usd: payout-services/advcash_wallet_usd/index.md
      -
        Bank_card_kzt: payout-services/bank_card_kzt/index.md
      -
        Bank_card_rub: payout-services/bank_card_rub/index.md
      -
        Bank_card_uah: payout-services/bank_card_uah/index.md
      -
        Payment_card_holder_rub: payout-services/payment_card_holder_rub/index.md
      -
        Payment_card_kzt: payout-services/payment_card_kzt/index.md
      -
        Payment_card_rub: payout-services/payment_card_rub/index.md
      -
        Payment_card_uah: payout-services/payment_card_uah/index.md
      -
        Qiwi_rub: payout-services/qiwi_rub/index.md
  -
    'Payment methods':
      -
        Alandsbanken: payment-methods/alandsbanken/index.md
      -
        Alfaclick: payment-methods/alfaclick/index.md
      -
        Bancoitau: payment-methods/bancoitau/index.md
      -
        Bancopastor: payment-methods/bancopastor/index.md
      -
        Bigconlinepayment: payment-methods/bigconlinepayment/index.md
      -
        Bitcoin: payment-methods/bitcoin/index.md
      -
        Bpay: payment-methods/bpay/index.md
      -
        Bradescocomercioeletronico: payment-methods/bradescocomercioeletronico/index.md
      -
        Citadelelatvia: payment-methods/citadelelatvia/index.md
      -
        Elektronischeslastschriftverfahren: payment-methods/elektronischeslastschriftverfahren/index.md
      -
        Enetsdirectdebit: payment-methods/enetsdirectdebit/index.md
      -
        Erstebank: payment-methods/erstebank/index.md
      -
        Ethereum: payment-methods/ethereum/index.md
      -
        Euroset: payment-methods/euroset/index.md
      -
        Euteller: payment-methods/euteller/index.md
      -
        Gemoney: payment-methods/gemoney/index.md
      -
        Hdfcbanknetbankingindia: payment-methods/hdfcbanknetbankingindia/index.md
      -
        Ibox: payment-methods/ibox/index.md
      -
        Icicinetbanking: payment-methods/icicinetbanking/index.md
      -
        Ideal: payment-methods/ideal/index.md
      -
        Inghomepay: payment-methods/inghomepay/index.md
      -
        Ingspain: payment-methods/ingspain/index.md
      -
        Inteligo: payment-methods/inteligo/index.md
      -
        Jyskebank: payment-methods/jyskebank/index.md
      -
        Kasikornbankkbanknetbanking: payment-methods/kasikornbankkbanknetbanking/index.md
      -
        Komercnibanka: payment-methods/komercnibanka/index.md
      -
        Krungsrinetbanking: payment-methods/krungsrinetbanking/index.md
      -
        Krungthaibanknetbanking: payment-methods/krungthaibanknetbanking/index.md
      -
        Lacaixa: payment-methods/lacaixa/index.md
      -
        Libertybank: payment-methods/libertybank/index.md
      -
        Litecoin: payment-methods/litecoin/index.md
      -
        Mbank: payment-methods/mbank/index.md
      -
        Moneymail: payment-methods/moneymail/index.md
      -
        Octopus: payment-methods/octopus/index.md
      -
        Okpay: payment-methods/okpay/index.md
      -
        Otpbank: payment-methods/otpbank/index.md
      -
        Poppankki: payment-methods/poppankki/index.md
      -
        Pravexbank: payment-methods/pravexbank/index.md
      -
        Promsvyazbank: payment-methods/promsvyazbank/index.md
      -
        Provinciapagos: payment-methods/provinciapagos/index.md
      -
        Qazkombank: payment-methods/qazkombank/index.md
      -
        Rcbc: payment-methods/rcbc/index.md
      -
        Ripple: payment-methods/ripple/index.md
      -
        Safetypay: payment-methods/safetypay/index.md
      -
        Scbbanknetbanking: payment-methods/scbbanknetbanking/index.md
      -
        Sepacredittransfer: payment-methods/sepacredittransfer/index.md
      -
        Sepadirectdebit: payment-methods/sepadirectdebit/index.md
      -
        Spankki: payment-methods/spankki/index.md
      -
        Ssk: payment-methods/ssk/index.md
      -
        Tele2ru: payment-methods/tele2ru/index.md
      -
        Tescolotus: payment-methods/tescolotus/index.md
      -
        Trustly: payment-methods/trustly/index.md
      -
        Ukrsibbank: payment-methods/ukrsibbank/index.md
      -
        Unicredit: payment-methods/unicredit/index.md
      -
        Volksbank: payment-methods/volksbank/index.md
      -
        Vubbanka: payment-methods/vubbanka/index.md
      -
        Wiretransfer: payment-methods/wiretransfer/index.md
