site_name: 'OFT docs'

theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'images/favicon.ico'
  logo:
    icon: 'import_contacts'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  feature:
    tabs: true
  font:
    text: Roboto
    code: Roboto Mono

# Customization
extra:
  social:
    - type: 'facebook'
      link: 'https://facebook.com/paycore.io/'
    - type: 'twitter'
      link: 'https://twitter.com/paycoreio'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/paycore/'
    - type: 'github'
      link: 'https://github.com/paycoreio'
extra_css:
  - extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
      repo_url_shortener: true
      repo_url_shorthand: true
      user: paycoreio
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: flow
          class: uml-flowchart
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: sequence
          class: uml-sequence-diagram
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details

nav:
  -
    Providers:
      -
        Overview: providers/index.md
      -
        123x: providers/123x/index.md
      -
        1pay: providers/1pay/index.md
      -
        4bill: providers/4bill/index.md
      -
        Acceptance: providers/acceptance/index.md
      -
        Africanpaymentsolutions: providers/africanpaymentsolutions/index.md
      -
        Anycash: providers/anycash/index.md
      -
        Aramorpayments: providers/aramorpayments/index.md
      -
        Astropay: providers/astropay/index.md
      -
        Balticpay: providers/balticpay/index.md
      -
        Beanstream: providers/beanstream/index.md
      -
        Billtomobile: providers/billtomobile/index.md
      -
        Bips: providers/bips/index.md
      -
        Bitmerch: providers/bitmerch/index.md
      -
        Bitnet: providers/bitnet/index.md
      -
        Bitpay: providers/bitpay/index.md
      -
        Bscardservices: providers/bscardservices/index.md
      -
        Bucksnet: providers/bucksnet/index.md
      -
        Cardconnect: providers/cardconnect/index.md
      -
        Cashsender: providers/cashsender/index.md
      -
        Circulopayments: providers/circulopayments/index.md
      -
        Citopay: providers/citopay/index.md
      -
        Citruspay: providers/citruspay/index.md
      -
        Corvuspay: providers/corvuspay/index.md
      -
        Credorax: providers/credorax/index.md
      -
        Cxpay: providers/cxpay/index.md
      -
        Cyberbit: providers/cyberbit/index.md
      -
        Dalberry: providers/dalberry/index.md
      -
        Digitalriverworldpayments: providers/digitalriverworldpayments/index.md
      -
        Dineromail: providers/dineromail/index.md
      -
        Dinpay: providers/dinpay/index.md
      -
        Dlocal: providers/dlocal/index.md
      -
        Ecardsa: providers/ecardsa/index.md
      -
        Econtext: providers/econtext/index.md
      -
        Ecpss: providers/ecpss/index.md
      -
        Eospaymentsolutions: providers/eospaymentsolutions/index.md
      -
        Epay: providers/epay/index.md
      -
        Europayment: providers/europayment/index.md
      -
        Europaysolutions: providers/europaysolutions/index.md
      -
        Exacttransactions: providers/exacttransactions/index.md
      -
        Expercash: providers/expercash/index.md
      -
        Ezic: providers/ezic/index.md
      -
        Firstatlanticcommerce: providers/firstatlanticcommerce/index.md
      -
        Flashpay: providers/flashpay/index.md
      -
        Fondy: providers/fondy/index.md
      -
        Gestpay: providers/gestpay/index.md
      -
        Iyzipayments: providers/iyzipayments/index.md
      -
        Kortapay: providers/kortapay/index.md
      -
        Lateralpaymentsolutions: providers/lateralpaymentsolutions/index.md
      -
        Lianlianpay: providers/lianlianpay/index.md
      -
        Liqpay: providers/liqpay/index.md
      -
        Magnius: providers/magnius/index.md
      -
        Mangopay: providers/mangopay/index.md
      -
        Masterpayment: providers/masterpayment/index.md
      -
        Merchantscout: providers/merchantscout/index.md
      -
        Mollie: providers/mollie/index.md
      -
        Netmobileag: providers/netmobileag/index.md
      -
        Netpay: providers/netpay/index.md
      -
        Omnipayment: providers/omnipayment/index.md
      -
        Onpex: providers/onpex/index.md
      -
        Optomany: providers/optomany/index.md
      -
        Payanyway: providers/payanyway/index.md
      -
        Paybox: providers/paybox/index.md
      -
        Paycific: providers/paycific/index.md
      -
        Paydoo: providers/paydoo/index.md
      -
        Paymega: providers/paymega/index.md
      -
        Paymentexpress: providers/paymentexpress/index.md
      -
        Paymentgarage: providers/paymentgarage/index.md
      -
        Paymentgateway: providers/paymentgateway/index.md
      -
        Paymundo: providers/paymundo/index.md
      -
        Paystation: providers/paystation/index.md
      -
        Paytabs: providers/paytabs/index.md
      -
        Pinpayments: providers/pinpayments/index.md
      -
        Propay: providers/propay/index.md
      -
        Realexpayments: providers/realexpayments/index.md
      -
        Robokassa: providers/robokassa/index.md
      -
        Sbm: providers/sbm/index.md
      -
        Securepay: providers/securepay/index.md
      -
        Securionpay: providers/securionpay/index.md
      -
        Simplepay: providers/simplepay/index.md
      -
        Sisow: providers/sisow/index.md
      -
        Sixpaymentservices: providers/sixpaymentservices/index.md
      -
        Swishme: providers/swishme/index.md
      -
        Tefpay: providers/tefpay/index.md
      -
        Test: providers/test/index.md
      -
        Trustpay: providers/trustpay/index.md
      -
        Upclick: providers/upclick/index.md
      -
        Vallettapay: providers/vallettapay/index.md
      -
        Wayforpay: providers/wayforpay/index.md
      -
        Webmoney: providers/webmoney/index.md
      -
        Yandexcheckout: providers/yandexcheckout/index.md
      -
        Yandexmoney: providers/yandexmoney/index.md
      -
        Yapstone: providers/yapstone/index.md
      -
        Zaakpay: providers/zaakpay/index.md
  -
    'Payout services':
      -
        Overview: payout-services/index.md
      -
        Advcash_wallet_rub: payout-services/advcash_wallet_rub/index.md
      -
        Advcash_wallet_uah: payout-services/advcash_wallet_uah/index.md
      -
        Advcash_wallet_usd: payout-services/advcash_wallet_usd/index.md
      -
        Bank_card_kzt: payout-services/bank_card_kzt/index.md
      -
        Bank_card_rub: payout-services/bank_card_rub/index.md
      -
        Bank_card_uah: payout-services/bank_card_uah/index.md
      -
        Payment_card_holder_rub: payout-services/payment_card_holder_rub/index.md
      -
        Payment_card_kzt: payout-services/payment_card_kzt/index.md
      -
        Payment_card_rub: payout-services/payment_card_rub/index.md
      -
        Payment_card_uah: payout-services/payment_card_uah/index.md
      -
        Qiwi_rub: payout-services/qiwi_rub/index.md
  -
    'Payment methods':
      -
        Alandsbanken: payment-methods/alandsbanken/index.md
      -
        Alfaclick: payment-methods/alfaclick/index.md
      -
        Bancoitau: payment-methods/bancoitau/index.md
      -
        Bancopastor: payment-methods/bancopastor/index.md
      -
        Bigconlinepayment: payment-methods/bigconlinepayment/index.md
      -
        Bitcoin: payment-methods/bitcoin/index.md
      -
        Bpay: payment-methods/bpay/index.md
      -
        Bradescocomercioeletronico: payment-methods/bradescocomercioeletronico/index.md
      -
        Citadelelatvia: payment-methods/citadelelatvia/index.md
      -
        Elektronischeslastschriftverfahren: payment-methods/elektronischeslastschriftverfahren/index.md
      -
        Enetsdirectdebit: payment-methods/enetsdirectdebit/index.md
      -
        Erstebank: payment-methods/erstebank/index.md
      -
        Ethereum: payment-methods/ethereum/index.md
      -
        Euroset: payment-methods/euroset/index.md
      -
        Euteller: payment-methods/euteller/index.md
      -
        Gemoney: payment-methods/gemoney/index.md
      -
        Hdfcbanknetbankingindia: payment-methods/hdfcbanknetbankingindia/index.md
      -
        Ibox: payment-methods/ibox/index.md
      -
        Icicinetbanking: payment-methods/icicinetbanking/index.md
      -
        Ideal: payment-methods/ideal/index.md
      -
        Inghomepay: payment-methods/inghomepay/index.md
      -
        Ingspain: payment-methods/ingspain/index.md
      -
        Inteligo: payment-methods/inteligo/index.md
      -
        Jyskebank: payment-methods/jyskebank/index.md
      -
        Kasikornbankkbanknetbanking: payment-methods/kasikornbankkbanknetbanking/index.md
      -
        Komercnibanka: payment-methods/komercnibanka/index.md
      -
        Krungsrinetbanking: payment-methods/krungsrinetbanking/index.md
      -
        Krungthaibanknetbanking: payment-methods/krungthaibanknetbanking/index.md
      -
        Lacaixa: payment-methods/lacaixa/index.md
      -
        Libertybank: payment-methods/libertybank/index.md
      -
        Litecoin: payment-methods/litecoin/index.md
      -
        Mbank: payment-methods/mbank/index.md
      -
        Moneymail: payment-methods/moneymail/index.md
      -
        Octopus: payment-methods/octopus/index.md
      -
        Okpay: payment-methods/okpay/index.md
      -
        Otpbank: payment-methods/otpbank/index.md
      -
        Poppankki: payment-methods/poppankki/index.md
      -
        Pravexbank: payment-methods/pravexbank/index.md
      -
        Promsvyazbank: payment-methods/promsvyazbank/index.md
      -
        Provinciapagos: payment-methods/provinciapagos/index.md
      -
        Qazkombank: payment-methods/qazkombank/index.md
      -
        Rcbc: payment-methods/rcbc/index.md
      -
        Ripple: payment-methods/ripple/index.md
      -
        Safetypay: payment-methods/safetypay/index.md
      -
        Scbbanknetbanking: payment-methods/scbbanknetbanking/index.md
      -
        Sepacredittransfer: payment-methods/sepacredittransfer/index.md
      -
        Sepadirectdebit: payment-methods/sepadirectdebit/index.md
      -
        Spankki: payment-methods/spankki/index.md
      -
        Ssk: payment-methods/ssk/index.md
      -
        Tele2ru: payment-methods/tele2ru/index.md
      -
        Tescolotus: payment-methods/tescolotus/index.md
      -
        Trustly: payment-methods/trustly/index.md
      -
        Ukrsibbank: payment-methods/ukrsibbank/index.md
      -
        Unicredit: payment-methods/unicredit/index.md
      -
        Volksbank: payment-methods/volksbank/index.md
      -
        Vubbanka: payment-methods/vubbanka/index.md
      -
        Wiretransfer: payment-methods/wiretransfer/index.md
